[STREAM-146] - Update logging for new JSON-RPC commands.
purecloudlabs/genesys-cloud-streaming-client pull request #259
Opened 2024-07-31 19:38 UTC by zservies

2024-07-31 19:40 UTC, maxwellmooney13 approved these changes

2024-07-31 19:43 UTC, zservies commented
Dave didn't mention it in the ticket, but should we not also update messages for rejects/retracts - `sending jingle reject` to `sending jingle session-terminate (reject)` and `sending jingle session-terminate (retract)`?

2024-07-31 20:06 UTC, jensengar requested changes

2024-07-31 20:06 UTC, jensengar commented on src/webrtc.ts
> +    this.logger.info('sending jingle session-accept', details);
You'll also need to add the corresponding log in `GenesysCloudMediaSession.accept()`

2024-07-31 20:06 UTC, jensengar commented on src/webrtc.ts
> +      this.logger.info('Emitting jingle media-session (session-init)', session);
The sdp counterpart for this is in `webrtc.handleGenesysOffer()`

2024-08-01 14:04 UTC, jensengar commented
> Dave didn't mention it in the ticket, but should we not also update messages for rejects/retracts - `sending jingle reject` to `sending jingle session-terminate (reject)` and `sending jingle session-terminate (retract)`?

terminate/session-terminate, yes.
reject and retract are stanza messages and aren't changing. we will continue to use them even when using sdpOverXmpp so  nothing needs to happen there.

2024-08-05 11:48 UTC, jensengar commented on src/types/genesys-cloud-media-session.ts
> +    this.logger.info('sending jingle session-accept', params);
this should be `sending sdp answer`

2024-08-06 13:00 UTC, jensengar approved these changes

2024-08-07 19:30 UTC, merged